\qecho Inserting ISO 639-2 Language codes...

select rlm.register_component ( 'CIN', 'ins_communication_lanuages.sql' );

begin;

insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'aar','','aa','Afar','afar');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'abk','','ab','Abkhazian','abkhaze');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ace','','','Achinese','aceh');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ach','','','Acoli','acoli');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ada','','','Adangme','adangme');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ady','','','Adyghe; Adygei','adyghé');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'afa','','','Afro-Asiatic languages','afro-asiatiques, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'afh','','','Afrihili','afrihili');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'afr','','af','Afrikaans','afrikaans');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ain','','','Ainu','aïnou');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'aka','','ak','Akan','akan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'akk','','','Akkadian','akkadien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'alb','sqi','sq','Albanian','albanais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ale','','','Aleut','aléoute');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'alg','','','Algonquian languages','algonquines, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'alt','','','Southern Altai','altai du Sud');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'amh','','am','Amharic','amharique');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ang','','','English, Old (ca.450-1100)','anglo-saxon (ca.450-1100)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'anp','','','Angika','angika');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'apa','','','Apache languages','apaches, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ara','','ar','Arabic','arabe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'arc','','','Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)','araméen d''empire (700-300 BCE)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'arg','','an','Aragonese','aragonais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'arm','hye','hy','Armenian','arménien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'arn','','','Mapudungun; Mapuche','mapudungun; mapuche; mapuce');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'arp','','','Arapaho','arapaho');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'art','','','Artificial languages','artificielles, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'arw','','','Arawak','arawak');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'asm','','as','Assamese','assamais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ast','','','Asturian; Bable; Leonese; Asturleonese','asturien; bable; léonais; asturoléonais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ath','','','Athapascan languages','athapascanes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'aus','','','Australian languages','australiennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ava','','av','Avaric','avar');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ave','','ae','Avestan','avestique');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'awa','','','Awadhi','awadhi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'aym','','ay','Aymara','aymara');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'aze','','az','Azerbaijani','azéri');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bad','','','Banda languages','banda, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bai','','','Bamileke languages','bamiléké, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bak','','ba','Bashkir','bachkir');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bal','','','Baluchi','baloutchi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bam','','bm','Bambara','bambara');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ban','','','Balinese','balinais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'baq','eus','eu','Basque','basque');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bas','','','Basa','basa');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bat','','','Baltic languages','baltes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bej','','','Beja; Bedawiyet','bedja');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bel','','be','Belarusian','biélorusse');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bem','','','Bemba','bemba');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ben','','bn','Bengali','bengali');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ber','','','Berber languages','berbères, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bho','','','Bhojpuri','bhojpuri');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bih','','bh','Bihari','bihari');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bik','','','Bikol','bikol');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bin','','','Bini; Edo','bini; edo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bis','','bi','Bislama','bichlamar');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bla','','','Siksika','blackfoot');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bnt','','','Bantu (Other)','bantoues, autres langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bos','','bs','Bosnian','bosniaque');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bra','','','Braj','braj');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bre','','br','Breton','breton');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'btk','','','Batak languages','batak, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bua','','','Buriat','bouriate');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bug','','','Buginese','bugi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bul','','bg','Bulgarian','bulgare');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'bur','mya','my','Burmese','birman');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'byn','','','Blin; Bilin','blin; bilen');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cad','','','Caddo','caddo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cai','','','Central American Indian languages','amérindiennes de L''Amérique centrale, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'car','','','Galibi Carib','karib; galibi; carib');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cat','','ca','Catalan; Valencian','catalan; valencien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cau','','','Caucasian languages','caucasiennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ceb','','','Cebuano','cebuano');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cel','','','Celtic languages','celtiques, langues; celtes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cha','','ch','Chamorro','chamorro');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chb','','','Chibcha','chibcha');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'che','','ce','Chechen','tchétchène');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chg','','','Chagatai','djaghataï');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chi','zho','zh','Chinese','chinois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chk','','','Chuukese','chuuk');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chm','','','Mari','mari');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chn','','','Chinook jargon','chinook, jargon');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cho','','','Choctaw','choctaw');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chp','','','Chipewyan; Dene Suline','chipewyan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chr','','','Cherokee','cherokee');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chu','','cu','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic','slavon d''église; vieux slave; slavon liturgique; vieux bulgare');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chv','','cv','Chuvash','tchouvache');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'chy','','','Cheyenne','cheyenne');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cmc','','','Chamic languages','chames, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cop','','','Coptic','copte');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cor','','kw','Cornish','cornique');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cos','','co','Corsican','corse');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cpe','','','Creoles and pidgins, English based','créoles et pidgins basés sur l''anglais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cpf','','','Creoles and pidgins, French-based ','créoles et pidgins basés sur le français');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cpp','','','Creoles and pidgins, Portuguese-based ','créoles et pidgins basés sur le portugais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cre','','cr','Cree','cree');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'crh','','','Crimean Tatar; Crimean Turkish','tatar de Crimé');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'crp','','','Creoles and pidgins ','créoles et pidgins');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'csb','','','Kashubian','kachoube');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cus','','','Cushitic languages','couchitiques, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'cze','ces','cs','Czech','tchèque');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dak','','','Dakota','dakota');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dan','','da','Danish','danois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dar','','','Dargwa','dargwa');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'day','','','Land Dayak languages','dayak, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'del','','','Delaware','delaware');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'den','','','Slave (Athapascan)','esclave (athapascan)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dgr','','','Dogrib','dogrib');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'din','','','Dinka','dinka');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'div','','dv','Divehi; Dhivehi; Maldivian','maldivien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'doi','','','Dogri','dogri');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dra','','','Dravidian languages','dravidiennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dsb','','','Lower Sorbian','bas-sorabe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dua','','','Duala','douala');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dum','','','Dutch, Middle (ca.1050-1350)','néerlandais moyen (ca. 1050-1350)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dut','nld','nl','Dutch; Flemish','néerlandais; flamand');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dyu','','','Dyula','dioula');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'dzo','','dz','Dzongkha','dzongkha');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'efi','','','Efik','efik');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'egy','','','Egyptian (Ancient)','égyptien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'eka','','','Ekajuk','ekajuk');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'elx','','','Elamite','élamite');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'eng','','en','English','anglais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'enm','','','English, Middle (1100-1500)','anglais moyen (1100-1500)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'epo','','eo','Esperanto','espéranto');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'est','','et','Estonian','estonien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ewe','','ee','Ewe','éwé');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ewo','','','Ewondo','éwondo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fan','','','Fang','fang');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fao','','fo','Faroese','féroïen');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fat','','','Fanti','fanti');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fij','','fj','Fijian','fidjien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fil','','','Filipino; Pilipino','filipino; pilipino');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fin','','fi','Finnish','finnois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fiu','','','Finno-Ugrian languages','finno-ougriennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fon','','','Fon','fon');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fre','fra','fr','French','français');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'frm','','','French, Middle (ca.1400-1600)','français moyen (1400-1600)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fro','','','French, Old (842-ca.1400)','français ancien (842-ca.1400)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'frr','','','Northern Frisian','frison septentrional');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'frs','','','Eastern Frisian','frison oriental');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fry','','fy','Western Frisian','frison occidental');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ful','','ff','Fulah','peul');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'fur','','','Friulian','frioulan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gaa','','','Ga','ga');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gay','','','Gayo','gayo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gba','','','Gbaya','gbaya');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gem','','','Germanic languages','germaniques, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'geo','kat','ka','Georgian','géorgien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ger','deu','de','German','allemand');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gez','','','Geez','guèze');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gil','','','Gilbertese','kiribati');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gla','','gd','Gaelic; Scottish Gaelic','gaélique; gaélique écossais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gle','','ga','Irish','irlandais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'glg','','gl','Galician','galicien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'glv','','gv','Manx','manx; mannois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gmh','','','German, Middle High (ca.1050-1500)','allemand, moyen haut (ca. 1050-1500)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'goh','','','German, Old High (ca.750-1050)','allemand, vieux haut (ca. 750-1050)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gon','','','Gondi','gond');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gor','','','Gorontalo','gorontalo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'got','','','Gothic','gothique');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'grb','','','Grebo','grebo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'grc','','','Greek, Ancient (to 1453)','grec ancien (jusqu''à 1453)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gre','ell','el','Greek, Modern (1453-)','grec moderne (après 1453)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'grn','','gn','Guarani','guarani');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gsw','','','Swiss German; Alemannic; Alsatian','suisse alémanique; alémanique; alsacien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'guj','','gu','Gujarati','goudjrati');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'gwi','','','Gwich''in','gwich''in');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hai','','','Haida','haida');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hat','','ht','Haitian; Haitian Creole','haïtien; créole haïtien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hau','','ha','Hausa','haoussa');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'haw','','','Hawaiian','hawaïen');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'heb','','he','Hebrew','hébreu');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'her','','hz','Herero','herero');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hil','','','Hiligaynon','hiligaynon');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'him','','','Himachali','himachali');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hin','','hi','Hindi','hindi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hit','','','Hittite','hittite');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hmn','','','Hmong','hmong');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hmo','','ho','Hiri Motu','hiri motu');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hrv','','hr','Croatian','croate');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hsb','','','Upper Sorbian','haut-sorabe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hun','','hu','Hungarian','hongrois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'hup','','','Hupa','hupa');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'iba','','','Iban','iban');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ibo','','ig','Igbo','igbo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ice','isl','is','Icelandic','islandais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ido','','io','Ido','ido');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'iii','','ii','Sichuan Yi; Nuosu','yi de Sichuan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ijo','','','Ijo languages','ijo, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'iku','','iu','Inuktitut','inuktitut');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ile','','ie','Interlingue; Occidental','interlingue');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ilo','','','Iloko','ilocano');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ina','','ia','Interlingua (International Auxiliary Language Association)','interlingua (langue auxiliaire internationale)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'inc','','','Indic languages','indo-aryennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ind','','id','Indonesian','indonésien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ine','','','Indo-European languages','indo-européennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'inh','','','Ingush','ingouche');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ipk','','ik','Inupiaq','inupiaq');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ira','','','Iranian languages','iraniennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'iro','','','Iroquoian languages','iroquoises, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ita','','it','Italian','italien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'jav','','jv','Javanese','javanais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'jbo','','','Lojban','lojban');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'jpn','','ja','Japanese','japonais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'jpr','','','Judeo-Persian','judéo-persan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'jrb','','','Judeo-Arabic','judéo-arabe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kaa','','','Kara-Kalpak','karakalpak');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kab','','','Kabyle','kabyle');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kac','','','Kachin; Jingpho','kachin; jingpho');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kal','','kl','Kalaallisut; Greenlandic','groenlandais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kam','','','Kamba','kamba');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kan','','kn','Kannada','kannada');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kar','','','Karen languages','karen, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kas','','ks','Kashmiri','kashmiri');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kau','','kr','Kanuri','kanouri');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kaw','','','Kawi','kawi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kaz','','kk','Kazakh','kazakh');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kbd','','','Kabardian','kabardien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kha','','','Khasi','khasi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'khi','','','Khoisan languages','khoïsan, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'khm','','km','Central Khmer','khmer central');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kho','','','Khotanese; Sakan','khotanais; sakan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kik','','ki','Kikuyu; Gikuyu','kikuyu');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kin','','rw','Kinyarwanda','rwanda');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kir','','ky','Kirghiz; Kyrgyz','kirghiz');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kmb','','','Kimbundu','kimbundu');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kok','','','Konkani','konkani');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kom','','kv','Komi','kom');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kon','','kg','Kongo','kongo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kor','','ko','Korean','coréen');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kos','','','Kosraean','kosrae');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kpe','','','Kpelle','kpellé');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'krc','','','Karachay-Balkar','karatchai balkar');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'krl','','','Karelian','carélien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kro','','','Kru languages','krou, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kru','','','Kurukh','kurukh');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kua','','kj','Kuanyama; Kwanyama','kuanyama; kwanyama');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kum','','','Kumyk','koumyk');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kur','','ku','Kurdish','kurde');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'kut','','','Kutenai','kutenai');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lad','','','Ladino','judéo-espagnol');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lah','','','Lahnda','lahnda');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lam','','','Lamba','lamba');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lao','','lo','Lao','lao');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lat','','la','Latin','latin');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lav','','lv','Latvian','letton');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lez','','','Lezghian','lezghien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lim','','li','Limburgan; Limburger; Limburgish','limbourgeois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lin','','ln','Lingala','lingala');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lit','','lt','Lithuanian','lituanien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lol','','','Mongo','mongo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'loz','','','Lozi','lozi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ltz','','lb','Luxembourgish; Letzeburgesch','luxembourgeois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lua','','','Luba-Lulua','luba-lulua');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lub','','lu','Luba-Katanga','luba-katanga');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lug','','lg','Ganda','ganda');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lui','','','Luiseno','luiseno');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lun','','','Lunda','lunda');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'luo','','','Luo (Kenya and Tanzania)','luo (Kenya et Tanzanie)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'lus','','','Lushai','lushai');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mac','mkd','mk','Macedonian','macédonien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mad','','','Madurese','madourais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mag','','','Magahi','magahi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mah','','mh','Marshallese','marshall');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mai','','','Maithili','maithili');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mak','','','Makasar','makassar');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mal','','ml','Malayalam','malayalam');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'man','','','Mandingo','mandingue');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mao','mri','mi','Maori','maori');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'map','','','Austronesian languages','austronésiennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mar','','mr','Marathi','marathe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mas','','','Masai','massaï');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'may','msa','ms','Malay','malais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mdf','','','Moksha','moksa');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mdr','','','Mandar','mandar');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'men','','','Mende','mendé');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mga','','','Irish, Middle (900-1200)','irlandais moyen (900-1200)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mic','','','Mi''kmaq; Micmac','mi''kmaq; micmac');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'min','','','Minangkabau','minangkabau');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mis','','','Uncoded languages','langues non codées');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mkh','','','Mon-Khmer languages','môn-khmer, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mlg','','mg','Malagasy','malgache');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mlt','','mt','Maltese','maltais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mnc','','','Manchu','mandchou');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mni','','','Manipuri','manipuri');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mno','','','Manobo languages','manobo, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'moh','','','Mohawk','mohawk');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mon','','mn','Mongolian','mongol');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mos','','','Mossi','moré');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mul','','','Multiple languages','multilingue');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mun','','','Munda languages','mounda, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mus','','','Creek','muskogee');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mwl','','','Mirandese','mirandais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'mwr','','','Marwari','marvari');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'myn','','','Mayan languages','maya, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'myv','','','Erzya','erza');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nah','','','Nahuatl languages','nahuatl, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nai','','','North American Indian languages','nord-amérindiennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nap','','','Neapolitan','napolitain');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nau','','na','Nauru','nauruan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nav','','nv','Navajo; Navaho','navaho');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nbl','','nr','Ndebele, South; South Ndebele','ndébélé du Sud');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nde','','nd','Ndebele, North; North Ndebele','ndébélé du Nord');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ndo','','ng','Ndonga','ndonga');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nds','','','Low German; Low Saxon; German, Low; Saxon, Low','bas allemand; bas saxon; allemand, bas; saxon, bas');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nep','','ne','Nepali','népalais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'new','','','Nepal Bhasa; Newari','nepal bhasa; newari');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nia','','','Nias','nias');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nic','','','Niger-Kordofanian languages','nigéro-kordofaniennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'niu','','','Niuean','niué');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nno','','nn','Norwegian Nynorsk; Nynorsk, Norwegian','norvégien nynorsk; nynorsk, norvégien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nob','','nb','Bokmål, Norwegian; Norwegian Bokmål','norvégien bokmål');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nog','','','Nogai','nogaï; nogay');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'non','','','Norse, Old','norrois, vieux');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nor','','no','Norwegian','norvégien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nqo','','','N''Ko','n''ko');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nso','','','Pedi; Sepedi; Northern Sotho','pedi; sepedi; sotho du Nord');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nub','','','Nubian languages','nubiennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nwc','','','Classical Newari; Old Newari; Classical Nepal Bhasa','newari classique');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nya','','ny','Chichewa; Chewa; Nyanja','chichewa; chewa; nyanja');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nym','','','Nyamwezi','nyamwezi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nyn','','','Nyankole','nyankolé');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nyo','','','Nyoro','nyoro');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'nzi','','','Nzima','nzema');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'oci','','oc','Occitan (post 1500); Provençal','occitan (après 1500); provençal');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'oji','','oj','Ojibwa','ojibwa');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ori','','or','Oriya','oriya');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'orm','','om','Oromo','galla');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'osa','','','Osage','osage');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'oss','','os','Ossetian; Ossetic','ossète');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ota','','','Turkish, Ottoman (1500-1928)','turc ottoman (1500-1928)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'oto','','','Otomian languages','otomi, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'paa','','','Papuan languages','papoues, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pag','','','Pangasinan','pangasinan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pal','','','Pahlavi','pahlavi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pam','','','Pampanga; Kapampangan','pampangan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pan','','pa','Panjabi; Punjabi','pendjabi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pap','','','Papiamento','papiamento');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pau','','','Palauan','palau');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'peo','','','Persian, Old (ca.600-400 B.C.)','perse, vieux (ca. 600-400 av. J.-C.)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'per','fas','fa','Persian','persan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'phi','','','Philippine languages','philippines, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'phn','','','Phoenician','phénicien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pli','','pi','Pali','pali');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pol','','pl','Polish','polonais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pon','','','Pohnpeian','pohnpei');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'por','','pt','Portuguese','portugais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pra','','','Prakrit languages','prâkrit, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pro','','','Provençal, Old (to 1500)','provençal ancien (jusqu''à 1500)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'pus','','ps','Pushto; Pashto','pachto');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'que','','qu','Quechua','quechua');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'raj','','','Rajasthani','rajasthani');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'rap','','','Rapanui','rapanui');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'rar','','','Rarotongan; Cook Islands Maori','rarotonga; maori des îles Cook');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'roa','','','Romance languages','romanes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'roh','','rm','Romansh','romanche');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'rom','','','Romany','tsigane');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'rum','ron','ro','Romanian; Moldavian; Moldovan','roumain; moldave');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'run','','rn','Rundi','rundi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'rup','','','Aromanian; Arumanian; Macedo-Romanian','aroumain; macédo-roumain');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'rus','','ru','Russian','russe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sad','','','Sandawe','sandawe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sag','','sg','Sango','sango');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sah','','','Yakut','iakoute');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sai','','','South American Indian (Other)','indiennes d''Amérique du Sud, autres langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sal','','','Salishan languages','salishennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sam','','','Samaritan Aramaic','samaritain');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'san','','sa','Sanskrit','sanskrit');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sas','','','Sasak','sasak');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sat','','','Santali','santal');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'scn','','','Sicilian','sicilien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sco','','','Scots','écossais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sel','','','Selkup','selkoupe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sem','','','Semitic languages','sémitiques, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sga','','','Irish, Old (to 900)','irlandais ancien (jusqu''à 900)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sgn','','','Sign Languages','langues des signes');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'shn','','','Shan','chan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sid','','','Sidamo','sidamo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sin','','si','Sinhala; Sinhalese','singhalais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sio','','','Siouan languages','sioux, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sit','','','Sino-Tibetan languages','sino-tibétaines, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sla','','','Slavic languages','slaves, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'slo','slk','sk','Slovak','slovaque');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'slv','','sl','Slovenian','slovène');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sma','','','Southern Sami','sami du Sud');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sme','','se','Northern Sami','sami du Nord');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'smi','','','Sami languages','sames, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'smj','','','Lule Sami','sami de Lule');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'smn','','','Inari Sami','sami d''Inari');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'smo','','sm','Samoan','samoan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sms','','','Skolt Sami','sami skolt');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sna','','sn','Shona','shona');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'snd','','sd','Sindhi','sindhi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'snk','','','Soninke','soninké');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sog','','','Sogdian','sogdien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'som','','so','Somali','somali');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'son','','','Songhai languages','songhai, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sot','','st','Sotho, Southern','sotho du Sud');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'spa','','es','Spanish; Castilian','espagnol; castillan');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'srd','','sc','Sardinian','sarde');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'srn','','','Sranan Tongo','sranan tongo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'srp','','sr','Serbian','serbe');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'srr','','','Serer','sérère');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ssa','','','Nilo-Saharan languages','nilo-sahariennes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ssw','','ss','Swati','swati');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'suk','','','Sukuma','sukuma');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sun','','su','Sundanese','soundanais');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sus','','','Susu','soussou');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'sux','','','Sumerian','sumérien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'swa','','sw','Swahili','swahili');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'swe','','sv','Swedish','suédois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'syc','','','Classical Syriac','syriaque classique');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'syr','','','Syriac','syriaque');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tah','','ty','Tahitian','tahitien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tai','','','Tai languages','tai, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tam','','ta','Tamil','tamoul');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tat','','tt','Tatar','tatar');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tel','','te','Telugu','télougou');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tem','','','Timne','temne');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ter','','','Tereno','tereno');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tet','','','Tetum','tetum');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tgk','','tg','Tajik','tadjik');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tgl','','tl','Tagalog','tagalog');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tha','','th','Thai','thaï');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tib','bod','bo','Tibetan','tibétain');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tig','','','Tigre','tigré');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tir','','ti','Tigrinya','tigrigna');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tiv','','','Tiv','tiv');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tkl','','','Tokelau','tokelau');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tlh','','','Klingon; tlhIngan-Hol','klingon');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tli','','','Tlingit','tlingit');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tmh','','','Tamashek','tamacheq');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tog','','','Tonga (Nyasa)','tonga (Nyasa)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ton','','to','Tonga (Tonga Islands)','tongan (Îles Tonga)');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tpi','','','Tok Pisin','tok pisin');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tsi','','','Tsimshian','tsimshian');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tsn','','tn','Tswana','tswana');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tso','','ts','Tsonga','tsonga');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tuk','','tk','Turkmen','turkmène');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tum','','','Tumbuka','tumbuka');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tup','','','Tupi languages','tupi, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tur','','tr','Turkish','turc');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tut','','','Altaic languages','altaïques, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tvl','','','Tuvalu','tuvalu');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'twi','','tw','Twi','twi');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'tyv','','','Tuvinian','touva');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'udm','','','Udmurt','oudmourte');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'uga','','','Ugaritic','ougaritique');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'uig','','ug','Uighur; Uyghur','ouïgour');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ukr','','uk','Ukrainian','ukrainien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'umb','','','Umbundu','umbundu');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'und','','','Undetermined','indéterminée');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'urd','','ur','Urdu','ourdou');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'uzb','','uz','Uzbek','ouszbek');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'vai','','','Vai','vaï');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ven','','ve','Venda','venda');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'vie','','vi','Vietnamese','vietnamien');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'vol','','vo','Volapük','volapük');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'vot','','','Votic','vote');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'wak','','','Wakashan languages','wakashanes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'wal','','','Walamo','walamo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'war','','','Waray','waray');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'was','','','Washo','washo');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'wel','cym','cy','Welsh','gallois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'wen','','','Sorbian languages','sorabes, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'wln','','wa','Walloon','wallon');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'wol','','wo','Wolof','wolof');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'xal','','','Kalmyk; Oirat','kalmouk; oïrat');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'xho','','xh','Xhosa','xhosa');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'yao','','','Yao','yao');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'yap','','','Yapese','yapois');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'yid','','yi','Yiddish','yiddish');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'yor','','yo','Yoruba','yoruba');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'ypk','','','Yupik languages','yupik, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zap','','','Zapotec','zapotèque');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zbl','','','Blissymbols; Blissymbolics; Bliss','symboles Bliss; Bliss');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zen','','','Zenaga','zenaga');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zha','','za','Zhuang; Chuang','zhuang; chuang');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'znd','','','Zande languages','zandé, langues');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zul','','zu','Zulu','zoulou');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zun','','','Zuni','zuni');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zxx','','','No linguistic content; Not applicable','pas de contenu linguistique; non applicable');
insert into cin.communication_languages ( code_a3b, code_a3t, code_a2, english_name, french_name ) values ( 'zza','','','Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki','zaza; dimili; dimli; kirdki; kirmanjki; zazaki');
commit;

select rlm.component_registered ( 'ins_communication_lanuages.sql' );

\qecho ISO 639-2 Language codes inserted
